<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBcRFmTw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBcRFmTw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBcRFmTw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBcRFmTw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBcRFmTw\App_KernelDevDebugContainer([
    'container.build_hash' => 'BcRFmTw',
    'container.build_id' => '5cecf634',
    'container.build_time' => 1650457710,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBcRFmTw');
